In [14]:
import pandas as pd
import numpy as np
df_1y = pd.read_csv(r'/Users/liamrodgers/Library/CloudStorage/OneDrive-stevens.edu/FE800/Dal Pricing/DAL CDS/1Y_CDS_DAL.csv')
df_5y = pd.read_csv(r'/Users/liamrodgers/Library/CloudStorage/OneDrive-stevens.edu/FE800/Dal Pricing/DAL CDS/5Y_CDS_DAL.csv')
df_10y = pd.read_csv(r'/Users/liamrodgers/Library/CloudStorage/OneDrive-stevens.edu/FE800/Dal Pricing/DAL CDS/10Y_CDS_DAL.csv')

In [18]:
df_10y

      Day       Date    Price
0      Th  12/4/2025  102.490
1      We  12/3/2025  101.090
2      Tu  12/2/2025  102.155
3      Mo  12/1/2025  102.395
4     NaN        NaN      NaN
...   ...        ...      ...
3127   We  12/9/2015  275.000
3128   Tu  12/8/2015  275.000
3129   Mo  12/7/2015  275.000
3130  NaN        NaN      NaN
3131   Fr  12/4/2015  240.000

[3132 rows x 3 columns]

In [19]:
df_10y.drop(columns=['Day'], inplace=True)
df_10y.dropna(inplace=True)
df_10y

            Date    Price
0      12/4/2025  102.490
1      12/3/2025  101.090
2      12/2/2025  102.155
3      12/1/2025  102.395
5     11/28/2025  103.915
...          ...      ...
3126  12/10/2015  275.000
3127   12/9/2015  275.000
3128   12/8/2015  275.000
3129   12/7/2015  275.000
3131   12/4/2015  240.000

[2610 rows x 2 columns]

In [20]:
df_10y.to_csv('DAL_CDS_10Y_Cleaned.csv', index=False)